version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    container_name: nr
    environment:
      - TZ=America/Edmonton
    ports:
      - 1880:1880
    volumes:
      - node-red-data:/data
      - ./flows.json:/external/flows.json
      - ./flows_cred.json:/external/flows_cred.json
  pp:
    image: haumea/fireflyiii-pp:latest
    container_name: pp
    ports:
      - 9091:80
    volumes:
      - ./thunder-tests:/thunder
      - ./account-lookups:/keyValueStore
    environment:
      - DOTNET_KeyValueStoreSettings__Stores__assetAccounts__Path=assetAccounts.json
      - DOTNET_KeyValueStoreSettings__Stores__assetAccounts__DefaultValueValue={"attributes":{},"add_tags":[]}
      - DOTNET_KeyValueStoreSettings__Stores__expenseAccounts__Path=expenseAccounts.json
      - DOTNET_KeyValueStoreSettings__Stores__expenseAccounts__DefaultValueValue={"attributes":{},"add_tags":[]}
      - FireFlyIIISettings__BaseUrl=http://docker-selfhosted:8080/
      - FireFlyIIISettings__Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI0NyIsImp0aSI6ImJkNGVkYWU2ZDk3OWIxNDE4NzFmYjAzMjNmODAxYmYwYjhmODA0MTkxYjlmMWZmMjQyOWRkYTM1MzdhNmU3ODllOWIwOTQ0NDYzZTFiMTA5IiwiaWF0IjoxNzA3MTUyNzk1LjM5ODE4NCwibmJmIjoxNzA3MTUyNzk1LjM5ODE4NiwiZXhwIjoxNzM4Nzc1MTk1LjM3NDg3OSwic3ViIjoiMSIsInNjb3BlcyI6W119.o3eKEa0um7k1LVhrMn57DXYJzyq1PpAg3MQaaG_PYsreQox6GqsGTHfg9pr0MTdAfSmuJHZNu5Oo-jWcIWAFHqbisO7IR-4smu36np74KgPkzGiG0hmji4oYASl7pgMZEA9BGaKh4P0BCm_6oneHofFAmO2ukrmUX-vJydlT5hB22C_3FVsRxUPrEGdvgEvzcbkC4-fYFpLbx2K66SqWOx4R5PAtCR2YTaxtlBou9RNl6m0N1Ecisk0hnbQrC5TlLpuQfApPY5oSFgIF9FtVgL50ErUPCFsj-_xDC_iGtiAPqKBn3sRP2oa7gUjiIlevLjkYDxSb1PxcsueG6YjXsJbY48PiRD0PXYS6VyDJ4Ii3rslIF2REHmfNFPoYeWE7n0aOB_9WbPjRAx4qIz6WtlBSzVT759LKyFH7Vy04wAbSZcR7xB2HxD43exz1DPTZRFIuT48ZjhV1UwonidipIoEz1z2H-atRAcBENNxthYtWepp-UH_MDmkSF_YmvSDh4FStg8ze6s8xKbbdRpLSWRNQ3-9J3SNExbWdI0lw5xJaer_wF6nM4HQCPjiq7NqadkKA7CjX5kLaVBbGq-ZJSPZ7SZ4wqASbxMr2k_wKX_OAjx0ls4cCFijFKY2LbyLIVJomnP479UTHkXbScD9LubWK_MmNqJ3dvvqtdIsHR-k

volumes:
  node-red-data:
